---
build_from:
  aarch64: python:3.9-alpine
  amd64: python:3.9-alpine
  armhf: python:3.9-alpine
  armv7: python:3.9-alpine
  i386: python:3.9-alpine
labels:
  io.hass.type: addon
  io.hass.version: "1.0.0"
args:
  BUILD_FROM: python:3.9-alpine 